inputObj=open('C:/Users/prana/d1/input.txt','r')
Line_len_data=inputObj.readlines()
print(Line_len_data)
#Data = list(enumerate(Line_len_data))
print(Line_len_data)
print(type(Line_len_data[0]))
a = int(Line_len_data[0])
b = int(Line_len_data[1])
print(a)
print(b)
c = a+b
print(c)
print(type(c))
inputObj.close()
outputObj = open('C:/Users/prana/d1/input.txt','w')
outputObj.write(str(c))
outputObj.close()
